version: "3"
services:
  database:
    image: postgres:15
    container_name: directus-database
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
  directus:
    build:
      context: ./
    container_name: directus-cms
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    ports:
      - 8055:8055
    volumes:
      - ./extensions:/directus/extensions
      - ./templates:/directus/templates
      - ./uploads:/directus/uploads
      - ./snapshot:/directus/snapshot
    env_file:
      - .env
    environment:
      # Database
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      # Default Admin
      ADMIN_EMAIL: "hello@example.com"
      ADMIN_PASSWORD: "password"
